---
title: "Champions League Games 2025 Analysis"
author: "Jan Lopich"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Installing Packages
```{r}
#install.packages(c("readr", "readxl"))

library(readxl)
library(readr)
```


## Downloading Data
```{r}

clData = read_csv("champions_league_matches.csv")
clData

```


## Data Cleaning
```{r}

clData$home_possession = as.numeric(gsub("%", "", clData$home_possession)) 
clData$away_possession = as.numeric(gsub("%", "", clData$away_possession))

clData$home_goals <- as.numeric(sub("–.*", "", clData$score))
clData$away_goals <- as.numeric(sub("*.–", "", clData$score))

colnames(clData)[colnames(clData) == "home_passing_accuracy_pct"] = "homePassAcc"

clData

```


## Possession vs Goals (Home)
```{r}
plot(clData$home_possession, 
     jitter(clData$home_goals, amount = 0.1),
     xlab = "Home Possession (%)",
     ylab = "Home Goals",
     main = "Home Possession vs Goals Scored",
     pch = 16,
     col = rgb(0, 0, 1, 0.6))  # Semi-transparent blue

modelA = lm(home_goals ~ home_possession, data = clData)
abline(modelA, col = "red", lwd = 2) 


```


## Possession vs Goals (Overall)
```{r}
possession = c(clData$home_possession, clData$away_possession)
goals = c(clData$home_goals, clData$away_goals)

plot(possession, goals,
     xlab = "Possession (%)",
     ylab = "Goals Scored",
     main = "Possession vs Goals",
     pch = 16,
     col = rgb(0, 0, 1, 0.5))

abline(lm(goals ~ possession), col = "green", lwd = 2)

# PMMC
cor.test(possession, goals)


```


## Passing Accuracy vs Goals Scored 
```{r}
passingAccuracy = clData$homePassAcc
modelC = lm(home_goals ~ homePassAcc, data = clData)

plot(passingAccuracy, 
     jitter(clData$home_goals, amount = 0.1),
     xlab = "Passing Accuracy (%)",
     ylab = "Home Goals",
     main = "Passing Accuracy vs Goals Scored",
     pch = 16,
     col = rgb(0, 0, 1, 0.7))  

abline(modelC, col = "darkblue", lwd = 2) 

# PMMC
cor.test(passingAccuracy, clData$home_goals)
```
