---
title: "Nightlife at Warwick Analysis"
author: "Jan Lopich"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


## Installing Packages
```{r}
library(readxl)
library(readr)
```


## Downloading Data
```{r}
nightLifeData = read_excel("Nightlife Warwick.xlsx")
nightLifeData
```


## Fixing Data Set
```{r} 
nightLifeData$`Start time` = NULL
nightLifeData$`Completion time` = NULL
nightLifeData$`Email` = NULL

colnames(nightLifeData)[colnames(nightLifeData) == "What is your preferred time to get to the club usually?"] = "EntryTime"

colnames(nightLifeData)[colnames(nightLifeData) == "What time would you usually leave the club?"] = "ExitTime" 

colnames(nightLifeData)[colnames(nightLifeData) == "How would you rate the nightlife at Warwick (including Leamington Spa and Coventry)?"] = "Rating"
```


## Data Cleaning
```{r}

entry = as.POSIXct(substr(nightLifeData$EntryTime, 1, 5), format = "%H:%M")
exit = as.POSIXct(substr(nightLifeData$ExitTime, 1, 5), format = "%H:%M")

#nightLifeData$time_spent = NULL
nightLifeData$TimeSpent = as.numeric(difftime(exit, entry, units = "hours")) 

nightLifeData$TimeSpent = ifelse(nightLifeData$TimeSpent < 0, 
                                 nightLifeData$TimeSpent + 24, 
                                 nightLifeData$TimeSpent)

nightLifeData$TimeSpent = ifelse(nightLifeData$Name == "Prem Savani", 
                                 nightLifeData$TimeSpent + 3, 
                                 nightLifeData$TimeSpent)


nightLifeData

```


## Plotting Data
```{r}

plot(nightLifeData$TimeSpent, 
     nightLifeData$Rating,
     xlab = "Time Spent Clubbing",
     ylab = "Final Rating", 
     main = "Time Clubbing VS Final Rating",
     pch = 16, 
     col = "blue"
     ) 

modelW = lm(Rating ~ TimeSpent, data = nightLifeData)

abline(modelW, col="red", lwd=2) 

nightLifeData
```


## Statistical Data
```{r}
# Model Summary
summary(modelW)

# Correlation Test
cor.test(nightLifeData$TimeSpent, nightLifeData$Rating)

```

